name: Rails CI/CD
## ↓実行タイミング
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy
        # ↓環境変数
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          USER_NAME: ${{ secrets.USER_NAME }}
          HOST_NAME: ${{ secrets.HOST_NAME }}
        # ↓実行したいコマンド
        run: |
          echo "-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEAm0BR1XhtXHJpR4hXhAzN5Bicn0lCpTWNo0QU5oSPjSfKGCambq0U
D6mvQ8ChsgKqXhY2YBJWYjUuEZNGWnpy7H3xCOY8nCYbwsjV0uia4SFQXbe5fWXIXilBTw
pHuTPV1yZKfvowoVV6gMGAMh61KJbkbBtQGrTR92VCdT0qvZTV1Sc5Q6pQj8UGmnpZYiQV
Y5g3qcUU99AmvblTQbavKzZPHrAA4hk4vEhs+u+Nl4OG4swbWYqIkMTeQ4EGU5dCgpsWDn
b/VBVUDOlTsBZ8JD4LeTesyedZdEeevjdS0xkPH67tpR2x3JdYx3pC/Km5THspmd4W99uN
WD4CROfrCUS2Kd12oV9vaBh5Vda6mj1CiLvLZq8xz5jVfDnOcQuuY4enAgECvcGIIb5N8i
hlKai+vk6qED/HINphaaCOHQ6PdmA/E5Eq7jG3oRHEvGiKBBwx0MufCpcY2bQk/lqHdyVv
qXnXiHwVVn9152Q65Ss4KYYySYUo0mRVCLv6qEZRAAAFoJqKPHqaijx6AAAAB3NzaC1yc2
EAAAGBAJtAUdV4bVxyaUeIV4QMzeQYnJ9JQqU1jaNEFOaEj40nyhgmpm6tFA+pr0PAobIC
ql4WNmASVmI1LhGTRlp6cux98QjmPJwmG8LI1dLomuEhUF23uX1lyF4pQU8KR7kz1dcmSn
76MKFVeoDBgDIetSiW5GwbUBq00fdlQnU9Kr2U1dUnOUOqUI/FBpp6WWIkFWOYN6nFFPfQ
Jr25U0G2rys2Tx6wAOIZOLxIbPrvjZeDhuLMG1mKiJDE3kOBBlOXQoKbFg52/1QVVAzpU7
AWfCQ+C3k3rMnnWXRHnr43UtMZDx+u7aUdsdyXWMd6QvypuUx7KZneFvfbjVg+AkTn6wlE
tinddqFfb2gYeVXWupo9Qoi7y2avMc+Y1Xw5znELrmOHpwIBAr3BiCG+TfIoZSmovr5Oqh
A/xyDaYWmgjh0Oj3ZgPxORKu4xt6ERxLxoigQcMdDLnwqXGNm0JP5ah3clb6l514h8FVZ/
dedkOuUrOCmGMkmFKNJkVQi7+qhGUQAAAAMBAAEAAAGAdAqCYDWwQE5ABLiS+V98sUX4I1
Ll3oiFwofLu3VPuukHtD+HXOg/O2nQV6ru8Rfu8X5WzD5IlQU81uQmzNADgGKuO8Gjge82
BsSIlilIQofdAv+lRGZEeqUJbKO5cmOdLUAwpHIq0RwMAZsgT9YGAD2wpGFR4XRQEEN+hh
TfEm7h2X2E3t+5cYyJ4AMdNi7UUenfiSSHBKdvnZWc9lwu1/Sy9LQHJPhHIOxdkL5nLd2g
f3qh4q6aXuLXYstYyDgg02mRNdc6PTY/tPY+nRPLwCv8rFoFg030JzepCArfKIzCO8RxTs
uO/sAhwmV1V+NzK9OIOVUtl/8LZIxFlmdCfWtMjh46mwKG6Q4TnqrQlOeGE0xosIjWeAoC
CaVkOEwFHosvsBdDVsUJt0ax8lczOEvdHiEFbGl1u0C8oT7ZKKiUkHnvD24+g9iq3+pE5G
qsK+LTDJJCMGbBMg0wf7We4dXaYnRx+sGgGrDlPGj9nzNOo6ClGri5RTGVKU0/rP1BAAAA
wQCwyXJXJWty9x6WkZUAasRZyInOYCf5GxbbOSHgxzn1XF6X1aEWPjGUSZ3YR6vivXEspH
W9yveO1N/bcNIsdN69U6NWsSDRxJnBrQqynFBh61vqgaz29kbprCt8vNr7evzwseDEyNNl
ShOqh+EP08NtX9twrcBW/jUXle5Kmkkssk2WtDKcT6aHVuZIp9ywDUmH72bLTcL5Ki2WxJ
UOKDWyXQ9bQj3sGhnXsH3e7glmplGK/MYsr3toRI5N7XLVHZEAAADBAMgyhL1OcJcQkrBH
d1JCNb6UVzDEh+0gZriCgdDj6S6Eb87pMLONmjbFFHg2Oso92VsJkXSRXzrXTaUP3mnCkg
6oRF13Wf5Eg+3wkwXMMqWltJ+mTMlhaRaLdAhuEOZEEkaYaxQu43CbieoOLsxjoWKcjZgm
JT/asFOO6CK2usnBUCRPIex+NJ6ugQg92dog+ul/hsycXrluqpun8RDgO8uiveZSlA2U7y
vmJuaBRF+JJP/tQxCs+FdetBJP95CW2QAAAMEAxoaVQrYTDjAJyK08KLgziqOMeAjwqvGl
7hJyhte8eA9XrcMNLFy/RIl6/MlV0s+n/GeF/Fnl96kSix0SKYW48oMDtsI+eY1EYAkytX
+IDmMvDXssZzSxj7zPRRvkxVDe8lBsJ2WZq4pCHP2vphLVmeN316gNrDBrd1Fmlq6R6bsa
k10+p7p1Z0T3fn99tRImiD6ys6zQhF5htLxBqDiQX/6yqNtI0JuN7xmOpoFhmoRVgg7Uyr
NIY+29CwAH3jA5AAAAJnN1emFraXlvaWNoaUBzdXNha2lub01hY0Jvb2stQWlyLmxvY2Fs
AQIDBA==
-----END OPENSSH PRIVATE KEY-----" > private_key && chmod 600 private_key
          ssh -i private_key ${USER_NAME}@${HOST_NAME} 'cd re_bookers_2  &&
            git pull origin main &&
            ~/.rbenv/shims/bundle install &&
            ~/.rbenv/shims/bundle exec rails assets:precompile RAILS_ENV=production &&
            ~/.rbenv/shims/bundle exec rails db:migrate RAILS_ENV=production &&
            if [ -e tmp/pids/puma.pid ]];then sudo kill $(cat tmp/pids/puma.pid); echo kill puma process; fi &&
            ~/.rbenv/shims/rails s -e production'
